apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    # Custom PostgreSQL settings for replication
    wal_level = replica
    max_wal_senders = 10
    synchronous_commit = on
    synchronous_standby_names = '*'
    hot_standby = on
  pg_hba.conf: |
    # Allow replication connections from all IPs
    host replication all all md5

