apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-external
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: LoadBalancer

